### ISSUE TITLE
vim.lsp.diagnostic.get_count is deprecated. See :h deprecated

### ISSUE THREAD

**Issue by PercyDLR** [beauwilliams/statusline.lua#12]
Hi, I'm currenty using this plugin in Nvim 0.6.1. I can use the plugin with normallity, but I get a warning everytime I use Nvim that says
`vim.lsp.diagnostic.get_count is deprecated. See :h deprecated`, which is annoying and also, as it says, this function is going to be eliminated in future updates.

![Screenshot_2022-01-11_22:23:12](https://user-images.githubusercontent.com/92818861/149058320-35e7c79f-659f-4b12-b482-448a17e1d401.png)

I've found that this is used in the file `{PLUGIN_DIRECTORY}/statusline.lua/lua/sections/_lsp.lua` at line 16. I'd tried to fix it myself but I didn't have enough knowledge to do it lol.

I'm reporting this issue anyways.

**Comment by beauwilliams** [comment]
I can sort this out, I will put in a check for the newer versions to use vim.diagnostic instead let me have a look

**Comment by beauwilliams** [comment]
All done 👍 Let me know if you have issues still

**Comment by PercyDLR** [comment]
Everything is working fine and the message dissapeared, thanks!
