### ISSUE TITLE
expected lua number error

### ISSUE THREAD

**Issue by juantascon** [beauwilliams/statusline.lua#14]
Getting this error on neovim nightly:

E5108: Error executing lua ...e/pack/deps/opt/statusline.lua/lua/sections/_buficon.lua:6: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_name'
        ...e/pack/deps/opt/statusline.lua/lua/sections/_buficon.lua:6: in function 'get_file_icon'
        .../pack/deps/opt/statusline.lua/lua/modules/statusline.lua:115: in function <.../pack/deps/opt/statusline.lua/lua/modules/statusline.lua:99>

**Comment by cfuendev** [comment]
Same here, Neovim 0.7 and this happened to me.

**Comment by beauwilliams** [comment]
Okay let me look into this and get it fixed up :)

**Comment by beauwilliams** [comment]
@juantascon @cfuendesign I have pushed a fix, lmk if you are having further issues 👍
