### ISSUE TITLE
Support for LSP diagnostics

### ISSUE THREAD

**Issue by tormodatt** [beauwilliams/statusline.lua#4]
When using LSP, beeing notified in the status-line that there are errors and/or warnings is very useful, compared to skimming the whole document manually. A red/organge indicator with the number of errors/warnings to the right hand side of the statusline would be great!

https://github.com/nvim-lua/lsp-status.nvim has support for this, but I like this plugin better as lsp-status is more like a status-line API, and I don't need, or want to configure, that level of flexibility.

**Comment by beauwilliams** [comment]
Hello, I apologise for the delay. Been a few busy months with university just getting back into things.

I have now published a branch for you to test. It has LSP diags enabled. Let me know how you go!

You can find the folder where statusline.lua is installed, `cd ` to it, run `git pull` and then `git checkout lsp-status-2021`

I will add some more code soon and merge it to the main codebase and publish instructions on how to choose lsp or ale for diags.

**Comment by beauwilliams** [comment]
Please see here I have merged this enhancement into the master branch. Thanks for trying out my plugin mate, let me know if you have issues with this feature

https://github.com/beauwilliams/statusline.lua/commit/5db1abec851849c923dcb85ce38eef2d8e6d9552
