### ISSUE TITLE
Error at start StatusLine

### ISSUE THREAD

**Issue by TeoDev1611** [beauwilliams/statusline.lua#8]
![image](https://user-images.githubusercontent.com/73144037/124839874-46502500-df4f-11eb-93ee-cee8048efe0d.png)
![image](https://user-images.githubusercontent.com/73144037/124839887-4e0fc980-df4f-11eb-9e38-a04ea627f6c1.png)

I got this errors when start the statusline

> I use Dein as a plugin manager

**Comment by wizard-28** [comment]
Install [`nvim-lightbulb`](https://github.com/kosayoda/nvim-lightbulb)

**Comment by beauwilliams** [comment]
I will get this fixed asap. You should not need to install nvim-lightbulb, but for now that will fix the issue :)

**Comment by ayoubelmhamdi** [comment]
if you use packer 
```
   use 'kosayoda/nvim-lightbulb'
   use 'beauwilliams/statusline.lua'
```
you must note this recomendation in redme of yhis plugin

**Comment by beauwilliams** [comment]
> if you use packer
> 
> ```
>    use 'kosayoda/nvim-lightbulb'
>    use 'beauwilliams/statusline.lua'
> ```
> 
> you must note this recomendation in redme of yhis plugin

fixed now :)

no need to have lightbulb anymore, totally optional
